default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
