default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100gemfile

development:
  adapter: postgresql
  encoding: unicode
  database: range_force
  pool: 5
  username: buka
  password: "123456789"

test:
  adapter: postgresql
  encoding: unicode
  database: range_force_test
  pool: 5
  username: buka
  password: "123456789"
